import Head from "next/head";

import { Layout } from "@/features/layout";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ChatMessage } from "@/features/chat-message";
import { Button } from "@/components/ui/button";
import { useStore } from "@/hooks/useStore";
import { getChatCompletion } from "@/lib/langchain";

export default function Home() {
  const { message, messageHistory, setMessage, addMessageToHistory } =
    useStore();
  const model = "Mistral";

  const handleSendMessage = async () => {
    addMessageToHistory({
      body: message?.body ?? "",
      author: "you",
    });
    const msg = await getChatCompletion(message?.body ?? "");

    addMessageToHistory({
      body: msg.response,
      author: model,
    });

    console.log(msg);
  };

  return (
    <>
      <Head>
        <title>OllamaWrapper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex h-full w-full flex-col justify-between p-4">
          <ScrollArea className="min-h-[80vh]">
            {
              // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
              messageHistory!.map((msg, index) => (
                <ChatMessage key={index} author={msg.author}>
                  {msg.body}
                </ChatMessage>
              ))
            }
          </ScrollArea>
          <div className="grid w-full gap-2">
            <Textarea
              className="w-full"
              value={message?.body}
              onChange={(e) =>
                setMessage({
                  body: e.target.value,
                  author: "you",
                })
              }
              placeholder={`Message ${model}...`}
            />
            <Button onClick={handleSendMessage}>Send message</Button>
          </div>
        </div>
      </Layout>
    </>
  );
}
