import Head from "next/head";

import { Layout } from "@/features/layout";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ChatMessage } from "@/features/chat-message";
import { Button } from "@/components/ui/button";
import { useStore } from "@/hooks/useStore";
import { getMessage } from "@/lib/langchain";

export default function Home() {
  const { message, setMessage } = useStore();
  const model = "Mistral";

  const handleSendMessage = async () => {
    const msg = await getMessage(message);
    console.log(msg);
  };

  return (
    <>
      <Head>
        <title>OllamaWrapper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex h-full w-full flex-col justify-between p-4">
          <ScrollArea className="min-h-[80vh]">
            <ChatMessage author="you">
              Tell me about the top 10 productivity tools of 2023?
            </ChatMessage>
            <ChatMessage author={model}>I don&apos;t know.</ChatMessage>
          </ScrollArea>
          <div className="grid w-full gap-2">
            <Textarea
              className="w-full"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder={`Message ${model}...`}
            />
            <Button onClick={handleSendMessage}>Send message</Button>
          </div>
        </div>
      </Layout>
    </>
  );
}
